services:
  multi-agent-ide-postgres:
    image: localhost:5005/postgres-pgvector
    container_name: multi-agent-ide-postgres
    networks:
      multi-agent-ide-network:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - multi-agent-ide:/var/lib/postgresql/embedding
    ports:
      - "5105:5432"
volumes:
  multi-agent-ide:
networks:
  multi-agent-ide-network: