services:
  multi-agent-ide-postgres:
    image: localhost:5005/postgres-pgvector
    container_name: multi-agent-ide-postgres
    networks:
      multi-agent-ide-network:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /Users/hayde/db/artifact-db:/var/lib/postgresql/embedding
    ports:
      - "5105:5432"
networks:
  multi-agent-ide-network: