logging.config: classpath:logback-multi-agent-ide.xml

multi-agent-embabel:
  chat-model:
    provider: acp
  acp:
    transport: stdio
    command: ${ACP_COMMAND:codex-acp}
    args: ${ACP_ARGS:--sandbox danger-full-access --ask-for-approval never --yolo true}
    working-directory: ${ACP_WORKING_DIR:}
    auth-method: chatgpt
#    env:
#      PATH:

acp.mcp:
  http:
    #    - name: deepwiki
    #      url: https://mcp.deepwiki.com/mcp
    #      headers:
    - name: hindsight
      url: http://localhost:8777/mcp/${HINDSIGHT_MEM_BANK:agentic-coding}
      headers:
