logging.config: classpath:logback-multi-agent-ide.xml

multi-agent-embabel:
  chat-model:
    provider: acp
  acp:
    transport: stdio
    command: goose acp
    args: ${ACP_ARGS:--extensions developer}
    working-directory: ${ACP_WORKING_DIR:}
    env:
      #    will throw an error if your on mac for some security ring
#      HOME: {{PROJECT_DIR}}/configs
      GOOSE_MODE: smart_approve
      GOOSE_DISABLE_SUBAGENTS: true

spring:
  lifecycle:
    timeout-per-shutdown-phase: 1s

acp.mcp:
  http:
    #    - name: deepwiki
    #      url: https://mcp.deepwiki.com/mcp
    #      headers:
    - name: hindsight
      url: http://localhost:8777/mcp/${HINDSIGHT_MEM_BANK:agentic-coding}
      headers:
