multi-agent-embabel:
  chat-model:
    provider: acp
  acp:
    transport: stdio
    command: goose acp
    working-directory: ${ACP_WORKING_DIR:}
    env:
      HOME: {{PROJ_DIR}}/configs

spring:
  lifecycle:
    timeout-per-shutdown-phase: 1s

acp.mcp:
  http:
    - name: deepwiki
      url: https://mcp.deepwiki.com/mcp
      headers:
    - name: hindsight
      url: http://localhost:8888/mcp
      headers:
